### ISSUE TITLE
sftp is throwing an error - what am I missing?

### ISSUE THREAD

**Issue by Ajar-Ajar** [LeanMeanFightingMachine/dploy#64]
Connecting to dev...
An error occurred when retrieving the local hash. { [Error: Command failed: fata
l: bad default revision 'HEAD'
] killed: false, code: 128, signal: null }

**Comment by lucasmotta** [comment]
Hey @Ajar-Ajar, it's very likely there's something wrong on your repository that dploy can't get the current revision - so it's not really an issue with dploy.

I know it's been a while now, but if you still want to test, try running this on your project:
```
git rev-parse HEAD
```

You will probably get the same error.
