### ISSUE TITLE
Excluding dploy.yaml by default

### ISSUE THREAD

**Issue by jaysalvat** [LeanMeanFightingMachine/dploy#67]
Hello,
Thanks for dploy.

The dploy.yaml must be excluded by default, preventing it to be uploaded by mistake on a server.
It's a huge security issue because it exposes the username / password of the FTP server.

I guess checking http://www.somesite.com/dploy.yaml on some random sites using dploy will expose some dangerous information.

Anyway, there is no good reason to upload the dploy.yaml to server IMHO.

What do you think about excluding it by default?

Cheers.

**Comment by lucasmotta** [comment]
Done on next version! :)

**Comment by jaysalvat** [comment]
Great! You rock thanks.
