### ISSUE TITLE
Upload .rev file at the end

### ISSUE THREAD

**Issue by asadm** [LeanMeanFightingMachine/dploy#78]
I use dploy heavily. Is there a way to upload .rev file at the end (after all other changes have been uploaded). So if the connection breaks in between, I can start uploading from beginning instead of going to ftp and manually uploading rest of the files? Since dploy will just check .rev and say no changes need to be uploaded.

Thanks!

**Comment by lucasmotta** [comment]
Hey @asadm, which version are you using?
On version 1.2.0 this should be happening!

**Comment by asadm** [comment]
My bad. I think this happens only when multiple upload slots are open. In that case, it is understandable.
